#!/bin/sh

# $Id$

cd package-macosx
rm -rf camllight.pkg camllight-rw.dmg camllight.dmg

package root camllight.info

size=`du -s camllight.pkg | cut -f 1`
size=`expr $size + 8192`

hdiutil create -sectors $size camllight-rw.dmg
name=`hdid -nomount camllight-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
newfs_hfs -v 'Caml Light' $name
hdiutil detach $name

name=`hdid camllight-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
if test -d "/Volumes/Caml Light"; then
  ditto -rsrcFork camllight.pkg "/Volumes/Caml Light/camllight.pkg"
else
  echo 'Unable to mount the disk image as "/Volumes/Caml Light"' >&2
  exit 3
fi
hdiutil detach $name

hdiutil convert camllight-rw.dmg -format UDZO -o camllight.dmg
