/* Convert constants from C headers to Caml */

#include "../runtime/mlvalues.h"
#include "../runtime/exec.h"
#include "../runtime/instruct.h"

main () {
  printf("(* Code generated by `constants.c'. *)\n");
  printf("(* Do not modify. *)\n\n");
  printf("let String_tag = %d;;\n", String_tag);
  printf("let Double_tag = %d;;\n", Double_tag);
  printf("let Trailer_size = %d;;\n", TRAILER_SIZE);
  printf("let Exec_magic = %d;;\n", EXEC_MAGIC);
  printf("let Instr_break = `%c`;;\n", BREAK);
  return (0);
}
