FILES= refman.tex lex.tex names.tex values.tex const.tex types.tex \
  patterns.tex expr.tex typedecl.tex directive.tex intf.tex impl.tex \
  exten.tex

TRANSF=../../tools/transf
VPATH=../refman

all: $(FILES)

clean:
	rm -f $(FILES)

.SUFFIXES:
.SUFFIXES: .etex .tex

.etex.tex:
	$(TRANSF) -html < $< > $*.tex

$(FILES): $(TRANSF)
