#!/bin/bash

# $Id$

cd package-macosx
rm -rf camllight.pkg camllight-rw.dmg

VERSION=`sed -n -e '/VERSION/s/.*"\([^"]*\)".*/\1/p' ../version.h`
VERSION_MAJOR=${VERSION%%.*}
VERSION_MINOR=${VERSION##*.}

cat >Description.plist <<EOF
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
          <key>IFPkgDescriptionDeleteWarning</key>
          <string></string>
          <key>IFPkgDescriptionDescription</key>
          <string>The Caml Light compiler and tools</string>
          <key>IFPkgDescriptionTitle</key>
          <string>Caml Light</string>
          <key>IFPkgDescriptionVersion</key>
          <string>${VERSION}</string>
  </dict>
  </plist>
EOF

cat >Info.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleGetInfoString</key>
        <string>Caml Light ${VERSION}</string>
        <key>CFBundleIdentifier</key>
        <string>fr.inria.caml-light</string>
        <key>CFBundleName</key>
        <string>Caml Light</string>
        <key>CFBundleShortVersionString</key>
        <string>${VERSION}</string>
        <key>IFMajorVersion</key>
        <integer>${VERSION_MAJOR}</integer>
        <key>IFMinorVersion</key>
        <integer>${VERSION_MINOR}</integer>
        <key>IFPkgFlagAllowBackRev</key>
        <true/>
        <key>IFPkgFlagAuthorizationAction</key>
        <string>AdminAuthorization</string>
        <key>IFPkgFlagDefaultLocation</key>
        <string>/usr/local</string>
        <key>IFPkgFlagInstallFat</key>
        <false/>
        <key>IFPkgFlagIsRequired</key>
        <false/>
        <key>IFPkgFlagRelocatable</key>
        <false/>
        <key>IFPkgFlagRestartAction</key>
        <string>NoRestart</string>
        <key>IFPkgFlagRootVolumeOnly</key>
        <true/>
        <key>IFPkgFlagUpdateInstalledLanguages</key>
        <false/>
        <key>IFPkgFormatVersion</key>
        <real>0.10000000149011612</real>
</dict>
</plist>
EOF

mkdir -p resources

#                                         stop here -> |
cat >resources/ReadMe.txt <<EOF
This package installs Caml Light version ${VERSION}.
You need Mac OS X 10.4.x (Tiger), with X11 and the
XCode tools (v2.2) installed.

Files will be installed in the following directories:

/usr/local/bin - command-line executables
/usr/local/lib/caml-light - library and support files
/usr/local/man - manual pages
EOF

mkdir -p root
chmod -R g-w root
sudo chown -R root:admin root

/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker \
  -build -p "`pwd`/camllight.pkg" -f "`pwd`/root" -i "`pwd`/Info.plist" \
  -d "`pwd`/Description.plist" -r "`pwd`/resources"

size=`du -s camllight.pkg | cut -f 1`
size=`expr $size + 8192`

hdiutil create -sectors $size camllight-rw.dmg
name=`hdid -nomount camllight-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
newfs_hfs -v 'Caml Light' $name
hdiutil detach $name

name=`hdid camllight-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
if test -d "/Volumes/Caml Light"; then
  ditto -rsrcFork camllight.pkg "/Volumes/Caml Light/camllight.pkg"
  cp resources/ReadMe.txt "/Volumes/Caml Light/"
else
  echo 'Unable to mount the disk image as "/Volumes/Caml Light"' >&2
  exit 3
fi
open "/Volumes/Caml Light"
hdiutil detach $name

rm -rf "camllight-${VERSION}.dmg"
hdiutil convert camllight-rw.dmg -format UDZO -o "camllight-${VERSION}.dmg"
