#!/bin/sh
TKDIR=../lib

mods=`sed -e 's/WIDGETOBJS=//' -e 's/\([a-z_]*\)\.zo/\1/g' \
                  $TKDIR/modules`

for m in `echo $mods | tr ' ' '\012' | sort`
do
echo "\\section*{Module {\\tt $m}}"
echo "\\addcontentsline{toc}{section}{Module {\\tt $m}}"
echo "\\begin{alltt}"
echo "\\input{$TKDIR/$m.mli}"
echo "\\end{alltt}"
done

